[package]
name = "cuda_blas"
version = "0.1.0"
authors = ["Peter Jin <peterhaijin@gmail.com>"]
license = "BSD-2-Clause"
description = "cuBLAS API bindings."
respository = "https://github.com/peterhj/libcuda_blas"
keywords = ["cuda", "blas", "cublas"]

[dependencies]
libc = "*"
cuda = { git = "https://github.com/peterhj/libcuda.git" }

[lib]
name = "cuda_blas"
path = "src/lib.rs"
